# Generated by Django 6.1.1 on 2026-09-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('ecommerce', 'E-Commerce'), ('saas', 'SaaS'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('other', 'Other')], max_length=50)),
                ('short_description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='projects/covers/')),
                ('featured', models.BooleanField(default=False)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('tools_used', models.CharField(blank=True, max_length=255)),
                ('challenge', models.TextField()),
                ('approach', models.TextField()),
                ('solution', models.TextField()),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('client_position', models.CharField(blank=True, max_length=100)),
                ('testimonial', models.TextField(blank=True)),
                ('metric_1_label', models.CharField(blank=True, max_length=100)),
                ('metric_1_value', models.CharField(blank=True, max_length=50)),
                ('metric_2_label', models.CharField(blank=True, max_length=100)),
                ('metric_2_value', models.CharField(blank=True, max_length=50)),
                ('metric_3_label', models.CharField(blank=True, max_length=100)),
                ('metric_3_value', models.CharField(blank=True, max_length=50)),
                ('metric_4_label', models.CharField(blank=True, max_length=100)),
                ('metric_4_value', models.CharField(blank=True, max_length=50)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='projects/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
